
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/navbar";
import Hero from "./components/hero";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={` bg-white   ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <div className="bg-black text-white text-sm lg:text-lg flex items-center justify-center   p-6"> 
    <h1 className="sm:text-sm" >Sign up and get 20% off to your first order. <a className="underline-offset-1" href="">Sign up now</a></h1>
    </div>
    <Navbar/>
        {children}
      </body>
    </html>
  );
}
